### ISSUE TITLE
Text Size(font size) Component の追加

### ISSUE THREAD

**Issue by Shiba-github** [Shiba-github/varia-ui#32]
- [x] コンポーネントの追加
- [ ] on offパネルへの追加
- [x] コードエリアとbutton viewへの反映

**Comment by Actlam** [comment]
fontsizeはメジャーな値なのでオン・オフするしなくてもいいのでは？

**Comment by Shiba-github** [comment]
初期状態で出しておくかどうかは議論の余地がありそうだけど、
オフにできないのはどうかと思うので、オンオフ自体はできるようにしておくべきだと思ってる

**Comment by Actlam** [comment]
それでいくとcolorとかBackgroundColorとかもオンオフパネル（cssCustomAreaのこと？）に入れるべき？
