### ISSUE TITLE
CSS Custom animation panelの追加

### ISSUE THREAD

**Issue by Shiba-github** [Shiba-github/varia-ui#58]
animation関連だけでかなり多くなりそうだと思ったので通常のスタイルとは分割する
タブみたいにしてクリックしたら通常スタイル<=>animationで切り替えられるようにする

**Comment by Actlam** [comment]
animation関連だけでmilestoneにしてもよさそう

**Comment by Shiba-github** [comment]
内容決まってないからmilestoneでアキレスと亀やることになりそう
